<?php
$conf['sy'] = array (
  'id' => 7,
  'pre' => 'pro',
  'name' => '产品',
  'table_lm' => 'pro_lm',
  'table_co' => 'pro_co',
  'need_lm' => true,
  'level_lm' => 0,
);
$conf['lm'] = array (
  'mlang' => true,
  'seo' => true,
  'add_lm' => true,
  'apname_lm' => false,
  'url_lm' => false,
  'f_body_lm' => true,
  'z_body_lm' => false,
  'img_sl_lm' => true,
  'con_att' => true,
  'tuijian' => false,
  'hot' => false,
  'pass' => true,
);
$conf['co'] = array (
  'mlang' => true,
  'seo' => true,
  'add_xx' => true,
  'apname' => false,
  'keyword' => false,
  'link_url' => false,
  'pro_can1' => false,
  'pro_can2' => false,
  'pro_can3' => false,
  'pro_can4' => false,
  'f_body' => true,
  'z_body' => true,
  't_body' => false,
  'g_body' => false,
  'img_sl' => true,
  'pic_sl' => false,
  'fil_sl' => false,
  'vid_sl' => false,
  'image' => true,
  'info' => false,
  'file' => false,
  'video' => false,
  'zu' => false,
  'wtime' => false,
  'ding' => true,
  'tuijian' => true,
  'hot' => false,
  'pass' => true,
);
?>