<?php
$conf['sy'] = array (
  'id' => 17,
  'pre' => 'demo',
  'name' => '样本',
  'table_lm' => 'demo_lm',
  'table_co' => 'demo_co',
  'need_lm' => true,
  'level_lm' => 0,
);
$conf['lm'] = array (
  'mlang' => true,
  'seo' => true,
  'add_lm' => true,
  'apname_lm' => false,
  'url_lm' => false,
  'f_body_lm' => false,
  'z_body_lm' => false,
  'img_sl_lm' => false,
  'con_att' => true,
  'tuijian' => false,
  'hot' => false,
  'pass' => false,
);
$conf['co'] = array (
  'mlang' => true,
  'seo' => true,
  'add_xx' => true,
  'apname' => true,
  'keyword' => true,
  'link_url' => true,
  'f_body' => true,
  'z_body' => true,
  'img_sl' => true,
  'pic_sl' => false,
  'fil_sl' => true,
  'vid_sl' => false,
  'image' => true,
  'info' => true,
  'file' => true,
  'video' => true,
  'zu' => true,
  'wtime' => false,
  'ding' => true,
  'tuijian' => false,
  'hot' => false,
  'pass' => true,
);
?>