<?php
$conf['sy'] = array (
  'id' => 22,
  'pre' => 'map',
  'name' => '地图',
  'table_lm' => 'map_lm',
  'table_co' => 'map_co',
  'need_lm' => true,
  'level_lm' => 0,
);
$conf['lm'] = array (
  'mlang' => false,
  'seo' => false,
  'add_lm' => true,
  'apname_lm' => false,
  'url_lm' => false,
  'f_body_lm' => false,
  'z_body_lm' => false,
  'img_sl_lm' => false,
  'con_att' => false,
  'tuijian' => false,
  'hot' => false,
  'pass' => false,
);
$conf['co'] = array (
  'mlang' => false,
  'seo' => false,
  'add_xx' => true,
  'apname' => false,
  'keyword' => false,
  'link_url' => false,
  'phone' => true,
  'address' => true,
  'zuobiao' => true,
  'f_body' => false,
  'z_body' => false,
  'img_sl' => false,
  'pic_sl' => false,
  'fil_sl' => false,
  'vid_sl' => false,
  'image' => false,
  'info' => false,
  'file' => false,
  'video' => false,
  'zu' => false,
  'wtime' => false,
  'ding' => true,
  'tuijian' => false,
  'hot' => false,
  'pass' => true,
);
?>