<?php
/*
 * 中文版
 * ============================================================================
 */
 
//全局
$lang['gl']['par']='参数错误';
$lang['gl']['exist']='该信息不存在或已删除';
$lang['gl']['result']='搜索结果';
$lang['gl']['back']='返回';
$lang['gl']['more']='更多';
$lang['gl']['mores']='查看更多';
$lang['gl']['service']='在线客服';
$lang['gl']['close']='关闭';
$lang['gl']['zhankai']='展开';
$lang['gl']['shouqi']='收起';
$lang['gl']['safecode']='验证码';
$lang['gl']['must']='%s必须填写';
$lang['gl']['mustall']='带*号的必须填写';
$lang['gl']['error']='%s错误';

//留言板 
$lang['book']['title']='标题';
$lang['book']['num']='数量';
$lang['book']['rename']='姓名';
$lang['book']['sex']='性别';
$lang['book']['sex1']='男';
$lang['book']['sex2']='女';
$lang['book']['phone']='电话';
$lang['book']['fax']='传真';
$lang['book']['email']='邮箱';
$lang['book']['qq']='QQ';
$lang['book']['wx']='微信';
$lang['book']['compname']='公司名称';
$lang['book']['address']='地址';
$lang['book']['post']='邮编';
$lang['book']['z_body']='内容';
$lang['book']['etip']='发送成功,邮件发送失败,请设置发件箱';
$lang['book']['sucess']='提交成功';
//显示留言板
$lang['book']['reply']='回复';
$lang['book']['message']='发表留言';

//在线下单 
$lang['orders']['title']='标题';
$lang['orders']['num']='数量';
$lang['orders']['rename']='姓名';
$lang['orders']['sex']='性别';
$lang['orders']['sex1']='男';
$lang['orders']['sex2']='女';
$lang['orders']['phone']='电话';
$lang['orders']['fax']='传真';
$lang['orders']['email']='邮箱';
$lang['orders']['qq']='QQ';
$lang['orders']['wx']='微信';
$lang['orders']['compname']='公司名称';
$lang['orders']['address']='地址';
$lang['orders']['post']='邮编';
$lang['orders']['z_body']='内容';
$lang['orders']['etip']='发送成功,邮件发送失败,请设置发件箱';
$lang['orders']['sucess']='提交成功';

//在线报名 
$lang['sign']['title']='标题';
$lang['sign']['num']='数量';
$lang['sign']['rename']='姓名';
$lang['sign']['sex']='性别';
$lang['sign']['sex1']='男';
$lang['sign']['sex2']='女';
$lang['sign']['phone']='电话';
$lang['sign']['fax']='传真';
$lang['sign']['email']='邮箱';
$lang['sign']['qq']='QQ';
$lang['sign']['wx']='微信';
$lang['sign']['compname']='公司名称';
$lang['sign']['address']='地址';
$lang['sign']['post']='邮编';
$lang['sign']['z_body']='内容';
$lang['sign']['etip']='发送成功,邮件发送失败,请设置发件箱';
$lang['sign']['sucess']='提交成功';

//人才招聘
$lang['job']['apply']='立即应聘';
$lang['job']['f_body']='任职要求';
$lang['job']['z_body']='职位描述';
$lang['job']['num']='招聘人数';
$lang['job']['address']='工作地区';
$lang['job']['stime']='开始时间';
$lang['job']['etime']='结束时间';
$lang['job']['result']='搜索结果';
$lang['job']['job_title']='职位';
$lang['job']['username']='姓名';
$lang['job']['phone']='电话';
$lang['job']['email']='邮箱';
$lang['job']['remark']='备注';
$lang['job']['up_sl']='简历';
$lang['job']['etip']='发送成功,邮件发送失败,请设置发件箱';
$lang['job']['sucess']='提交成功';

//经销商查询
$lang['age']['tip0']='代理查询 Proxy Query';
$lang['age']['tip1']='请输入代理商的电话或微信号';
$lang['age']['tip2']='输入电话或微信号';
$lang['age']['code1']='号码';
$lang['age']['loading']='强力查询中....';
$lang['age']['code2']='请输入号码';
$lang['age']['pinfan']='查询过于频繁，3秒后再试！';
$lang['age']['result']='查询无结果，请慎重购买';
$lang['age']['title']='经销商名';
$lang['age']['ageno']='代理编号';
$lang['age']['area']='代理地区';
$lang['age']['idcard']='身份证';
$lang['age']['wx']='微信号';
$lang['age']['qq']='QQ号';
$lang['age']['phone']='电话号码';
$lang['age']['stime']='授权日期';
$lang['age']['etime']='到期日期';
$lang['age']['f_body']='简要介绍';
$lang['age']['z_body']='详细介绍';

//防伪查询
$lang['code']['tip0']='防伪码查询';
$lang['code']['tip1']='请输入产品上的防伪码辨别真伪';
$lang['code']['code1']='防伪码';
$lang['code']['cod1']='防伪码1';
$lang['code']['cod2']='防伪码2';
$lang['code']['cod3']='防伪码3';
$lang['code']['cod4']='防伪码4';
$lang['code']['loading']='强力查询中....';
$lang['code']['code2']='请输入防伪码';
$lang['code']['pinfan']='查询过于频繁，3秒后再试！';
$lang['code']['result1']='查询无结果，有可能是假货';
$lang['code']['result2']='恭喜您，%s 编码的商品是正品';
$lang['code']['result3']='%s 编码在 %s 已被查询过，如是你自己查询的，就是正品，否则就是假货';
$lang['code']['result4']='查询无结果，有可能是假货';

//邮件订阅
$lang['email']['tip1']='请输入您的邮箱，订阅最新信息';
$lang['email']['code1']='邮箱';
$lang['email']['loading']='处理中....';
$lang['email']['code2']='请输入邮箱';
$lang['email']['error']='邮箱';
$lang['email']['result1']='该邮箱已订阅过邮件，无须重复提交';
$lang['email']['result2']='恭喜您，订阅成功';

//会员注册
$lang['preg']['title']='会员注册';
$lang['preg']['tip0']='会员注册';
$lang['preg']['tip1']='已经是会员了？%s登录&gt;&gt;%s';
$lang['preg']['username']='用户名';
$lang['preg']['username_tip']='4-20位字母+数字';
$lang['preg']['password']='密码';
$lang['preg']['confirmpassword']='确认密码';
$lang['preg']['rename']='姓名';
$lang['preg']['sex']='性别';
$lang['preg']['sex1']='男';
$lang['preg']['sex2']='女';
$lang['preg']['phone']='电话';
$lang['preg']['phone_tip']='电话格式：010-12345678或13012345678';
$lang['preg']['fax']='传真';
$lang['preg']['email']='邮箱';
$lang['preg']['qq']='QQ';
$lang['preg']['wx']='微信';
$lang['preg']['compname']='公司名称';
$lang['preg']['address']='地址';
$lang['preg']['post']='邮编';
$lang['preg']['safecode']='验证码';
$lang['preg']['exist']='该用户名已有人使用';

//会员登录
$lang['plogin']['title']='会员登录';
$lang['plogin']['tip0']='会员登录';
$lang['plogin']['tip1']='还不是会员？%s免费注册&gt;&gt;%s';
$lang['plogin']['username']='用户名';
$lang['plogin']['password']='密码';
$lang['plogin']['safecode']='验证码';
$lang['plogin']['exist']='用户名不存在';
$lang['plogin']['result1']='该用户未审核';
$lang['plogin']['result2']='该用户未通过';
$lang['plogin']['result3']='该用户已被屏蔽';

//会员修改密码
$lang['pwedit']['title']='会员登录';
$lang['pwedit']['ypassword']='原密码';
$lang['pwedit']['password']='新密码';
$lang['pwedit']['confirmpassword']='确认密码';
$lang['pwedit']['exist']='用户名不存在';
$lang['pwedit']['result']='原密码错误';
$lang['pwedit']['sucess']='修改成功';

//会员修改资料
$lang['pzedit']['title']='会员注册';
$lang['pzedit']['rename']='姓名';
$lang['pzedit']['sex']='性别';
$lang['pzedit']['sex1']='男';
$lang['pzedit']['sex2']='女';
$lang['pzedit']['phone']='电话';
$lang['pzedit']['phone_tip']='电话格式：010-12345678或13012345678';
$lang['pzedit']['fax']='传真';
$lang['pzedit']['email']='邮箱';
$lang['pzedit']['qq']='QQ';
$lang['pzedit']['wx']='微信';
$lang['pzedit']['compname']='公司名称';
$lang['pzedit']['address']='地址';
$lang['pzedit']['post']='邮编';
$lang['pzedit']['sucess']='修改成功';

//分页
$lang['pages']['home']='首页';
$lang['pages']['prev']='上一页';
$lang['pages']['next']='下一页';
$lang['pages']['last']='尾页';

//详细页面的上一个和下一个
$lang['show']['prev']='上一个';
$lang['show']['next']='下一个';
$lang['show']['prev1']='上一条';
$lang['show']['next1']='下一条';
$lang['show']['exist']='没有了';

//文件下载
$lang['files']['exist']='文件不存在';
?>